### ISSUE TITLE
crash on step with unusual rule

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#118] opened 2014-06-25 15:16 UTC
_From [bob.mari...@soartech.com](https://code.google.com/u/112017452463115290100/) on November 12, 2012 12:00:19_

I was lazy and didn't feel like looking up a proper wait rule, so I just hacked one together that I thought would work for the simple test I'm doing:

sp {wait
(state <s> ^superstate <ss>)
(<ss> -^operator.name wait)
-->
(<ss> ^operator <o> +)
(<o> ^name wait)
}

With this rule loaded, Soar crashes when I step. I did this in the Java debugger with 9.3.2 release, 64-bit, Windows 7. The dialog that comes up says an assert failed (image attached). This is especially strange since I wasn't expecting debug stuff to be included in a release build.

This is not a high priority fix in that it is not holding me back -- I'll go find the proper wait rule now :)

**Attachment:** [assert failed.png](http://code.google.com/p/soar/issues/detail?id=117)

_Original issue: http://code.google.com/p/soar/issues/detail?id=117_

**Comment by garfieldnate** [comment] 2015-02-20 10:42
Assuming that this is the correct production (markdown mangles the original one), this does not crash in 9.3.4:

    sp {wait
        (state <s> ^superstate <super>)
        (<s> -^operator.name wait)
        -->
        ( <s> ^operator <o> +)
        ( <o> ^name wait)
    }

**Comment by mazina** [comment] 2016-09-29 01:35
Duplicate of issue 196

**Closed by mazina** 2016-09-29 01:35 UTC
Labels: bug, duplicate, imported
