### ISSUE TITLE
soar client error failed to create a window

### ISSUE THREAD

**Issue by ayman823** [SoarGroup/Soar#433] opened 2024-02-20 15:27 UTC
pls fix this error for me soar client error:failed to create a window

**Comment by garfieldnate** [comment] 2024-02-20 17:24
Please tell me:
* your OS
* your Soar version
* what you did that triggered the error
* more details about the error. Is this message printed in the debugger? In your terminal?

**Comment by garfieldnate** [comment] 2024-05-17 04:40
I cannot reproduce your issue without further details, so I'm going to close this.

**Closed as completed by garfieldnate** 2024-05-17 04:40 UTC

**Comment by Sfifteen12** [comment] 2024-12-19 12:34
can u tell me how to fix same issue here

**Comment by garfieldnate** [comment] 2024-12-20 19:06
@Sfifteen12 Is this your issue? https://github.com/SoarGroup/Soar/issues/502

**Comment by noxuafk** [comment] 2025-01-16 16:03
o meu deu o mesmo erro e eu só instalei e tentei abrir

**Comment by brightindarkness** [comment] 2025-04-18 18:05
This is my issue too
Please tell how can i fix it

**Comment by garfieldnate** [comment] 2025-04-18 20:27
@brightindarkness This is not the Minecraft Soar project, in case that's what you were looking for.

**Comment by Sfifteen12** [comment] 2025-08-19 12:52
yea its been time since i quit mc bro also thanks
