### ISSUE TITLE
memory leaks with remote connection

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#45] opened 2014-06-25 15:15 UTC
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 01:07:42_

Description From Bob Marinier 2008-12-16 16:40:37 (-) [reply]
To reproduce:

0) Start with a debug or debug scu build.
1) Open two command prompt windows in the SoarLibrary/bin directory.
2) In the first one, do "java -jar SoarJavaDebugger .jar".
3) In the second one, do "java -jar SoarJavaDebugger .jar -remote".
4) Close the first debugger. This should close both debugger windows 
(unless
you've changed the default debugger settings).

Tons of memory leaks are reported by the second debugger (the first has 
none).
Many of them appear to be related to ElementXML.

Note that, to debug leaks in Java, you can set a memory leak breakpoint 
near
the bottom of sml_ClientInterface.i (in the Resources Files folder of the
ClientSMLJava project in Visual Studio). But this probably has nothing to 
do
with Java, so it might be worth the effort to reproduce it in C++.

_Original issue: http://code.google.com/p/soar/issues/detail?id=44_

**Comment by mazina** [comment] 2016-09-29 05:10
Duplicate of #254

**Closed by mazina** 2016-09-29 05:10 UTC
Labels: bug, duplicate, imported
