### ISSUE TITLE
After Downloading soar It doesnt launch

### ISSUE THREAD

**Issue by ZenIsTheGod** [SoarGroup/Soar#507] opened 2024-09-26 13:19 UTC
After i launched it said launch client. I clicked ok and then it showed error message. i downloaded today and i just wanna play pls help me

**Comment by garfieldnate** [comment] 2024-09-26 16:17
Is this the same issue? https://github.com/SoarGroup/Soar/issues/502

If not, please tell me your operating system name and version.

**Comment by ZenIsTheGod** [comment] 2024-09-27 11:03
yes same issue

**Comment by ZenIsTheGod** [comment] 2024-09-27 11:04
i use windows 10 and idk version

**Comment by garfieldnate** [comment] 2024-09-27 20:17
Okay, I'm closing this as a duplicate of #502. Please give that issue a 👍 , and try the workaround described there (click "more info" and tell Windows to run the binary anyway).

**Closed as completed by garfieldnate** 2024-09-27 20:17 UTC
